ControlObras/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from usuarios.views import ingresar, salir, usuario_forbidden
from django.conf.urls.static import static
from django.conf import settings


if settings.DEBUG is True:
    urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    url(r'^admin/', include('usuarios.urls',namespace='usuarios',app_name="usuarios")),
    url(r'^admin2/', admin.site.urls),
    url(r'^login/$', ingresar, {'homepage':'vista:index'}, name='ingresar'),
    url(r'^logout/$', salir, name='salir'),
    url(r'^403/$', usuario_forbidden, name='forbidden'),
    url(r'^(?P<slug>[-\w\d]+)/ncr/',include('ncr.urls', namespace='ncr', app_name="ncr")),
    url(r'^(?P<slug>[-\w\d]+)/followup/',include('fu.urls', namespace='fu', app_name="fu")),
    url(r'^(?P<slug>[-\w\d]+)/dr/',include('dr.urls', namespace='dr', app_name="dr")),
    url(r'^',include('vista.urls', namespace='vista', app_name="vista")),
]

dr/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from dr import views

urlpatterns = [
    url(r'^editar/actividad/ajax', views.actividad_ajax, name='actividad_ajax'),
    url(r'^editar/composicion/ajax', views.composicion_ajax, name='composicion_ajax'),
    url(r'^editar/(?P<dr_id>[0-9]+)/actividad/composicion/agregar', views.composicion_agregar, name='composicion_agregar'),
    url(r'^editar/(?P<dr_id>[0-9]+)/ordenar', views.dr_ordenar, name='dr_ordenar'),
    url(r'^editar/(?P<dr_id>[0-9]+)/actividad/agregar', views.actividad_agregar, name='actividad_agregar'),
    url(r'^editar/(?P<dr_id>[0-9]+)/actividad/eliminar', views.actividad_eliminar, name='actividad_eliminar'),
    url(r'^editar/(?P<dr_id>[0-9]+)/composicion/eliminar', views.composicion_eliminar, name='composicion_eliminar'),
    url(r'^editar/(?P<dr_id>[0-9]+)', views.editar, name='editar'),
    url(r'^reporte/(?P<dr_id>[0-9]+)', views.create_dr_word, name='reporte_dr_word'),
    url(r'^listado', views.listado, name='listado'),
    url(r'^agregar', views.agregar, name='agregar'),
    url(r'^borrar', views.borrar, name='borrar'),
]

fu/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from fu import views

urlpatterns = [
    url(r'^avance', views.avance, name='avance'),
    url(r'^dashboard_diario', views.dashboard_diario, name='dashboard-diario'),
    url(r'^dashboard_imagen', views.dashboard_imagen, name='dashboard-imagen'),
    url(r'^dashboard', views.dashboard, name='dashboard'),
    url(r'^componentes', views.componente, name='componentes'),
    url(r'^actividades/registro/(?P<slug_ag>[-\w\d]+)', views.ingreso, name='ingreso'),
    url(r'^actividades/(?P<str_estado>[-\w\d]+)/ordenar', views.ordenar_actividades, name='actividades-ordenar'),
    url(r'^actividades', views.actividades, name='actividades'),
    url(r'^planificacion', views.planificacion, name='planificacion'),
    url(r'^configuracion', views.configuracion, name='configuracion'),
    url(r'^download_config', views.download_config, name='download_config'),
    url(r'^planificacion', views.planificacion, name='planificacion'),
    url(r'^paradas/agregar', views.add_paradas, name='agregar-paradas'),
    url(r'^paradas/(?P<id>[0-9]+)/editar', views.edit_paradas, name='editar-paradas'),
    url(r'^paradas', views.paradas, name='paradas'),
    url(r'^reportes', views.reportes, name='reportes'),
    url(r'^status_componentes', views.status_componentes, name='status_componentes'),
    # url(r'^componente/crear', views.create_componente, name='componente-create')
]

ncr/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from ncr import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^observaciones/(?P<slug_ag>[-\w\d]+)/listado_fotos', views.imagenes_aerogenerador, name='imagenes_aerogenerador'),
    url(r'^observaciones/resumen', views.observaciones_resumen, name='observaciones-resumen'),
    url(r'^observaciones/duplicadas', views.observaciones_duplicadas, name='observaciones_duplicadas'),
    url(r'^observaciones/imagenes/ver', views.list_fotos, name='fotos-list'),
    url(r'^observaciones/(?P<observacion_id>[0-9]+)/ver', views.show_observacion, name='observaciones-show'),
    url(r'^observaciones/(?P<observacion_id>[0-9]+)/editar', views.add_observacion, name='observaciones-editar'),
    url(r'^observaciones/(?P<observacion_id>[0-9]+)/revision/agregar', views.add_revision, name='revisiones-add'),
    url(r'^observaciones/(?P<observacion_id>[0-9]+)/revision/(?P<revision_id>[0-9]+)/editar', views.add_revision, name='revisiones-editar'),
    url(r'^observaciones/agregar', views.add_observacion, name='observaciones-agregar'),
    url(r'^observaciones/eliminar', views.del_observacion, name='observaciones-eliminar'),
    url(r'^observaciones/cerrar', views.close_observacion, name='observaciones-cerrar'),
    url(r'^observaciones/imagenes/set_primary', views.primary_image, name='imagenes-primary'),
    url(r'^observaciones/imagenes/set_orden', views.set_orden, name='imagenes-orden'),
    url(r'^observaciones/imagenes/(?P<image_id>[0-9]+)/borrar', views.del_image, name='imagenes-delete'),
    url(r'^revision/(?P<revision_id>[0-9]+)/imagenes/agregar', views.add_images, name='imagenes-agregar'),
    url(r'^revision/(?P<revision_id>[0-9]+)/imagenes/listado', views.table_fotos, name='imagenes-listado'),
    url(r'^revision/eliminar', views.del_revision, name='revision-eliminar'),
    url(r'^observaciones/informeNCR', views.informe_ncr, name='informeNCR'),
    url(r'^observaciones/punchlist', views.punchlist, name='punchlist'),
    url(r'^observaciones/(?P<slug_ag>[-\w\d]+)', views.observaciones, name='observaciones'),
    url(r'^observadores', views.observadores, name='observadores'),
    url(r'^configuracion', views.configuracion, name='configuracion')

]

vista/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from vista import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^parque/borrar', views.del_parque, name='del_parque'),
    url(r'^(?P<slug>[-\w\d]+)/aerogeneradores', views.aerogeneradores, name='aerogeneradores'),
    url(r'^(?P<slug>[-\w\d]+)/configuracion', views.configuracion, name='configuracion'),
    url(r'^(?P<slug>[-\w\d]+)/', views.home, name='home'),
]

vista/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.template import defaultfilters
import logging
logger = logging.getLogger('oritec')


@python_2_unicode_compatible
class Aerogenerador(models.Model):
    idx = models.IntegerField()
    nombre = models.CharField(max_length=100)
    parque = models.ForeignKey('ParqueSolar', on_delete=models.CASCADE)
    slug = models.SlugField()

    class Meta:
        unique_together = (("parque", "idx"),("parque", "nombre"))

    def __str__(self):
        return '%s' % self.nombre

    def graphText(self):
        return '%s' % self.nombre

    def save(self, *args, **kwargs):
        self.slug = defaultfilters.slugify(self.nombre)
        super(Aerogenerador, self).save(*args, **kwargs)


def logos_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'logos/{0}'.format(filename)


def logos_excel_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'logos/excel/{0}'.format(filename)


def word_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'word/{0}'.format(filename)


def excel_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'excel/{0}'.format(filename)


@python_2_unicode_compatible
class ParqueSolar(models.Model):
    nombre = models.CharField(max_length=50)
    slug = models.SlugField(unique=True,null=True)
    cliente = models.CharField(max_length=100, default='')
    suministrador = models.CharField(max_length=100, default='')
    plataforma = models.CharField(max_length=100, default='')
    no_aerogeneradores = models.IntegerField(default=0)
    prev_no_aerogeneradores = models.IntegerField(default=0)
    codigo = models.CharField(max_length=50,unique=True)
    logo = models.ImageField(upload_to=logos_directory_path, max_length=500, null=True, blank=True)
    logo_excel = models.ImageField(upload_to=logos_excel_directory_path, max_length=500, null=True, blank=True)
    word = models.FileField(upload_to=word_directory_path, max_length=500, null=True, blank=True)
    excel_fu = models.FileField(upload_to=excel_directory_path, max_length=500, null=True, blank=True)
    pais = models.CharField(max_length=100, default='')
    region = models.CharField(max_length=100, default='')
    municipio = models.CharField(max_length=100, default='')

    class Meta:
        unique_together = ("nombre", "codigo")

    def __str__(self):
        return '%s' % self.nombre

    def getPrintName(self):
        return self.codigo + " " + self.nombre

    def create_excel_logo(self):
        # original code for this method came from
        # http://snipt.net/danfreak/generate-thumbnails-in-django-with-pil/

        # If there is no image associated with this.
        # do not create thumbnail
        if not self.logo:
            return

        original_image = self.logo

        from PIL import Image
        from cStringIO import StringIO
        from django.core.files.uploadedfile import SimpleUploadedFile
        import os

        # Set our max thumbnail size in a tuple (max width, max height)
        THUMBNAIL_SIZE = (800, 70)

        try:
            DJANGO_TYPE = original_image.file.content_type
        except Exception as e:
            if original_image.name.lower().endswith(".jpg"):
                DJANGO_TYPE = 'image/jpeg'
            elif original_image.name.lower().endswith(".png"):
                DJANGO_TYPE = 'image/png'
            elif original_image.name.lower().endswith(".JPG"):
                DJANGO_TYPE = 'image/jpeg'
            elif original_image.name.lower().endswith(".PNG"):
                DJANGO_TYPE = 'image/png'
            elif original_image.name.lower().endswith(".jpeg"):
                DJANGO_TYPE = 'image/jpeg'

        if DJANGO_TYPE == 'image/jpeg':
            PIL_TYPE = 'jpeg'
            FILE_EXTENSION = 'jpg'
        elif DJANGO_TYPE == 'image/png':
            PIL_TYPE = 'png'
            FILE_EXTENSION = 'png'

        # Open original photo which we want to thumbnail using PIL's Image
        image = Image.open(StringIO(original_image.read()))

        # We use our PIL Image object to create the thumbnail, which already
        # has a thumbnail() convenience method that contrains proportions.
        # Additionally, we use Image.ANTIALIAS to make the image look better.
        # Without antialiasing the image pattern artifacts may result.

        image.thumbnail(THUMBNAIL_SIZE, Image.ANTIALIAS)
        #return 0
        # Save the thumbnail
        temp_handle = StringIO()
        image.save(temp_handle, PIL_TYPE)
        temp_handle.seek(0)

        # Save image to a SimpleUploadedFile which can be saved into
        # ImageField
        suf = SimpleUploadedFile(os.path.split(original_image.name)[-1],
                                 temp_handle.read(), content_type=DJANGO_TYPE)
        # Save SimpleUploadedFile into image field
        self.logo_excel.save(
            '%s_thumbnail.%s' % (os.path.splitext(suf.name)[0], FILE_EXTENSION),
            suf,
            save=False
        )
        original_image.seek(0)

    def save(self, *args, **kwargs):
        self.slug = defaultfilters.slugify(self.codigo)

        updateThumbnail = True

        if self.pk is not None:
            orig = ParqueSolar.objects.get(pk=self.pk)
            if orig.logo == self.logo:
                updateThumbnail = False
            if self.logo_excel == '':
                updateThumbnail = True #Condicion inicial

        if updateThumbnail:
            try:
                self.create_excel_logo()
            except Exception as e:
                logger.debug(e.__doc__)
                logger.debug(e.message)

        force_update = False
        # self.create_reporte_img()
        # If the instance already has been saved, it has an id and we set
        # force_update to True
        if self.id:
            force_update = True

        # Force an UPDATE SQL query if we're editing the image to avoid integrity exception
        super(ParqueSolar, self).save(force_update=force_update)

vista/forms.py
# -*- coding: utf-8 -*-
from django import forms
from models import ParqueSolar

class ParqueFormFull(forms.ModelForm):
    class Meta:
        model = ParqueSolar
        fields = ['nombre','cliente','suministrador','plataforma','no_aerogeneradores','codigo','logo','word','excel_fu','pais','region','municipio']
        labels = {
            'no_aerogeneradores': 'Nº de Aerogeneradores',
            'word': 'Plantilla Word Informes NCR',
            'excel_fu': 'Plantilla Excel Informes FU',
        }
    def __init__(self, *args, **kwargs):
        super(ParqueFormFull, self).__init__(*args, **kwargs)
        self.fields['nombre'].widget.attrs['class'] = 'form-control'
        self.fields['cliente'].widget.attrs['class'] = 'form-control'
        self.fields['suministrador'].widget.attrs['class'] = 'form-control'
        self.fields['plataforma'].widget.attrs['class'] = 'form-control'
        self.fields['no_aerogeneradores'].widget.attrs['class'] = 'form-control'
        self.fields['codigo'].widget.attrs['class'] = 'form-control'
        self.fields['pais'].widget.attrs['class'] = 'form-control'
        self.fields['region'].widget.attrs['class'] = 'form-control'
        self.fields['municipio'].widget.attrs['class'] = 'form-control'


class ParqueForm(forms.ModelForm):
    class Meta:
        model = ParqueSolar
        fields = ['nombre','codigo']
    def __init__(self, *args, **kwargs):
        super(ParqueForm, self).__init__(*args, **kwargs)
        self.fields['nombre'].widget.attrs['class'] = 'form-control'
        self.fields['codigo'].widget.attrs['class'] = 'form-control'

vista/templates/footer.html
{% load staticfiles %}
<!-- BEGIN FOOTER -->
<div class="page-footer">
	<div class="page-footer-inner">
		 {% now "Y" %} &copy; Oritec SpA.
	</div>
	<div class="scroll-to-top">
		<i class="icon-arrow-up"></i>
	</div>
</div>
<!-- END FOOTER -->

vista/templates/header.html
{% load staticfiles %}
<!-- BEGIN HEADER -->
<div class="page-header navbar navbar-fixed-top" style="background-color: #2B4963;">
	<!-- BEGIN HEADER INNER -->
	<div class="page-header-inner">
		<!-- BEGIN LOGO -->
		<div class="page-logo">
			<a href="/">
			<img src="{% static 'common/images/saroenfull.png' %}" alt="logo" class="logo-default" style="margin-top:7px" height="30px"/>
			</a>
		</div>
		<!-- END LOGO -->
		<!-- BEGIN RESPONSIVE MENU TOGGLER -->
		<a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
				<span></span>
		</a>
		<!-- END RESPONSIVE MENU TOGGLER -->
		<!-- BEGIN TOP NAVIGATION MENU -->
		<div class="top-menu">
			<ul class="nav navbar-nav pull-right">
				<!-- BEGIN USER LOGIN DROPDOWN -->
				<li class="dropdown dropdown-user">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
					<img alt="" class="img-circle hide1" src="{% static 'common/images/Icon-Admin.png' %}"/>
					<span class="username username-hide-on-mobile">
					    {{user|title}}
                    </span>
					<i class="fa fa-angle-down"></i>
					</a>
					<ul class="dropdown-menu">

						<!--<li>
							<a href="extra_lock.html">
							<i class="icon-lock"></i> Bloquear pantalla </a>
						</li>-->
						<li>
							<a href="{% url 'salir' %}">
							<i class="icon-key"></i> Salir </a>
						</li>
					</ul>
				</li>
				<!-- END USER LOGIN DROPDOWN -->
				<!-- BEGIN QUICK SIDEBAR TOGGLER -->
				<!--<li class="dropdown dropdown-quick-sidebar-toggler">
					<a href="javascript:;" class="dropdown-toggle">
					<i class="icon-logout"></i>
					</a>
				</li>-->
				<!-- END QUICK SIDEBAR TOGGLER -->
			</ul>
		</div>
		<!-- END TOP NAVIGATION MENU -->
	</div>
	<!-- END HEADER INNER -->
</div>
<!-- END HEADER -->

vista/templates/sidebar.html
{% load staticfiles %}
{% load customtags %}

<!-- BEGIN SIDEBAR -->
<div class="page-sidebar-wrapper">
    <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
    <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
    <div class="page-sidebar navbar-collapse collapse">
        <!-- BEGIN SIDEBAR MENU -->
        <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
        <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
        <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
        <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
        <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
        <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
        <ul class="page-sidebar-menu page-header-fixed " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200" style="padding-top: 20px">
            <!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->

            <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
            <li class="sidebar-toggler-wrapper">
                <div class="sidebar-toggler">
                    <span></span>
                </div>
            </li>
            <!-- END SIDEBAR TOGGLER BUTTON -->
            &nbsp;
            <!--<li class="start ">-->
            <li class="nav-item start active open" id="menu-principal">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-home"></i>
                    <span class="title">Principal</span>
                    <span class="selected"></span>
                    <span class="arrow open"></span>
                </a>

                <ul class="sub-menu">
                    <li class="nav-item " id="menu2-resumen">
                        <a href="{% url 'vista:home' parque.slug %}" class="nav-link ">
                            <i class="fa fa-info-circle"></i>
                            <span class="title">Informaci&oacute;n Parque</span>

                        </a>
                    </li>
                    <!--El resto de los menú solo se muestran si la configuración existe...-->
                    {% if perms.vista.change_parquesolar %}
                        {% if parque.no_aerogeneradores > 0 %}
                            <li class="nav-item " id="menu2-observadores">
                                <a href="{% url 'ncr:observadores' parque.slug %}" class="nav-link ">
                                    <i class="fa fa-edit"></i>
                                    <span class="title">Inspectores</span>

                                </a>
                            </li>
                            <li class="nav-item " id="menu2-aerogeneradores">
                                <a href="{% url 'vista:aerogeneradores' parque.slug %}" class="nav-link ">
                                    <i class="fa fa-location-arrow"></i>
                                    <span class="title">Aerogeneradores</span>

                                </a>
                            </li>
                        {% endif %}
                        <li class="nav-item " id="menu2-configuracion">
                            <a href="{% url 'vista:configuracion' parque.slug %}" class="nav-link ">
                                <i class="fa fa-wrench"></i>
                                <span class="title">Configuraci&oacute;n</span>

                            </a>
                        </li>
                    {% endif %}
                </ul>
            </li>

            {% if parque.no_aerogeneradores > 0 %}
                <!--<li class="start ">-->
                <li class="nav-item" id="menu-ncr">
                    <a href="javascript:;" class="nav-link nav-toggle">
                        <i class="fa fa-edit"></i>
                        <span class="title">NCRs</span>
                        <span class="selected"></span>
                        <span class="arrow open"></span>
                    </a>
                    <ul class="sub-menu">
                        <li class="nav-item " id="menu2-observaciones-resumen">
                            <a href="{% url 'ncr:observaciones-resumen' parque.slug %}" class="nav-link ">
                                <i class="fa fa-caret-right"></i>
                                <span class="title">Resumen</span>
                            </a>
                        </li>
                        <li class="nav-item " id="menu2-informeNCR">
                            <a href="{% url 'ncr:informeNCR' parque.slug %}" class="nav-link ">
                                <i class="fa fa-caret-right"></i>
                                <span class="title">Informe NCRs</span>
                            </a>
                        </li>
                        <li class="nav-item " id="menu2-punchlist">
                            <a href="{% url 'ncr:punchlist' parque.slug %}" class="nav-link ">
                                <i class="fa fa-caret-right"></i>
                                <span class="title">Punchlist</span>
                            </a>
                        </li>
                        <li class="nav-item " id="menu2-duplicadas">
                            <a href="{% url 'ncr:observaciones_duplicadas' parque.slug %}" class="nav-link ">
                                <i class="fa fa-caret-right"></i>
                                <span class="title">Duplicadas</span>
                            </a>
                        </li>
                        {% if request.user.is_superuser %}
                            <li class="nav-item " id="menu2-configuracion-ncr">
                                <a href="{% url 'ncr:configuracion' parque.slug %}" class="nav-link ">
                                    <i class="fa fa-caret-right"></i>
                                    <span class="title">Configuración</span>
                                </a>
                            </li>
                        {% endif %}
                        {% for wtg in aerogeneradores %}
                            <li class="nav-item " id="menu2-observaciones-{{ wtg.idx }}">
                                <a href="{% url 'ncr:observaciones' parque.slug wtg.slug %}" class="nav-link ">
                                    <i class="fa fa-caret-right"></i>
                                    <span class="title">{{ wtg.nombre }}</span>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item" id="menu-fu">
                    <a href="javascript:;" class="nav-link nav-toggle">
                        <i class="fa fa-line-chart"></i>
                        <span class="title">Follow Up</span>
                        <span class="selected"></span>
                        <span class="arrow open"></span>
                    </a>
                    <ul class="sub-menu">
                        <li class="nav-item " id="menu2-dashboard">
                            <a href="{% url 'fu:dashboard' parque.slug %}" class="nav-link ">
                                <i class="fa fa-caret-right"></i>
                                <span class="title">Dashboard</span>
                            </a>
                        </li>
                        <li class="nav-item " id="menu2-dashboard-diario">
                            <a href="{% url 'fu:dashboard-diario' parque.slug %}" class="nav-link ">
                                <i class="fa fa-caret-right"></i>
                                <span class="title">Dashboard Diario</span>
                            </a>
                        </li>
                        {% if perms.fu.add_componente %}
                            <li class="nav-item " id="menu2-componentes">
                                <a href="{% url 'fu:componentes' parque.slug %}" class="nav-link ">
                                    <i class="fa fa-caret-right"></i>
                                    <span class="title">Componentes</span>
                                </a>
                            </li>
                        {% endif %}
                        {% if perms.fu.add_componentesparque %}
                            <li class="nav-item " id="menu2-actividades">
                                <a href="{% url 'fu:actividades' parque.slug %}" class="nav-link ">
                                    <i class="fa fa-caret-right"></i>
                                    <span class="title">Actividades</span>
                                </a>
                            </li>
                        {% endif %}
                        {% if perms.fu.add_configuracionfu %}
                            <li class="nav-item " id="menu2-configuracionfu">
                                <a href="{% url 'fu:configuracion' parque.slug %}" class="nav-link ">
                                    <i class="fa fa-caret-right"></i>
                                    <span class="title">Configuraci&oacute;n</span>
                                </a>
                            </li>
                        {% endif %}
                        <li class="nav-item " id="menu2-planificacion">
                            <a href="{% url 'fu:planificacion' parque.slug %}" class="nav-link ">
                                <i class="fa fa-caret-right"></i>
                                <span class="title">Planificaci&oacute;n</span>
                            </a>
                        </li>
                        <li class="nav-item " id="menu2-paradas">
                            <a href="{% url 'fu:paradas' parque.slug %}" class="nav-link ">
                                <i class="fa fa-caret-right"></i>
                                <span class="title">Listado de paradas</span>
                            </a>
                        </li>
                        <li class="nav-item " id="menu2-reportes">
                            <a href="{% url 'fu:reportes' parque.slug %}" class="nav-link ">
                                <i class="fa fa-caret-right"></i>
                                <span class="title">Reportes</span>
                            </a>
                        </li>
                        {% for wtg in aerogeneradores|filter_ag_fu %}
                            <li class="nav-item " id="menu2-ingreso-{{ wtg.idx }}">
                                <a href="{% url 'fu:ingreso' parque.slug wtg.slug %}" class="nav-link ">
                                    <i class="fa fa-caret-right"></i>
                                    <span class="title">{{ wtg.nombre }}</span>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
                {% if perms.dr.change_dr %}
                    <li class="nav-item" id="menu-dr">
                        <a href="javascript:;" class="nav-link nav-toggle">
                            <i class="fa fa-calendar"></i>
                            <span class="title">DR</span>
                            <span class="selected"></span>
                            <span class="arrow open"></span>
                        </a>
                        <ul class="sub-menu">
                            <li class="nav-item " id="menu2-listado">
                                <a href="{% url 'dr:listado' parque.slug %}" class="nav-link ">
                                    <i class="fa fa-caret-right"></i>
                                    <span class="title">Listado</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                {% endif %}
            {% endif %}
        </ul>
        <!-- END SIDEBAR MENU -->
    </div>
</div>
<!-- END SIDEBAR -->